version: '2'
services:
  nodejs:
    image: narwassco/vt-map
    build: .
    env_file:
      - ./app-docker.env
    volumes:
      - ./public:/tmp/src/vt-map/public
      - ./config.js:/tmp/src/vt-map/config.js
      - ./config-search.js:/tmp/src/vt-map/config-search.js   